config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  #originally devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' } # now we need to tell devise (extend) that when devise is about to register a user we need to know if pro or basic. we do this with a new controller called registrations
  
  #nested routes. These are routes to pull associated things
  #together such as profiles would naturally fall under
  #the user route
  resources :users do
    resource :profile #singular
  end
  
  get 'about', to: 'pages#about'
  resources :contacts, only: [:create]
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  #can be left blank by default, but if validation is needed
  #this is where it goes
  #Contact form validations
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  #each Plan can have many users
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    #each profile will belong to a user and each user has one profile
    belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  #each user should belong to a plan
  belongs_to :plan
  has_one :profile

  attr_accessor :stripe_card_token  #whitelist this field so that we can use it below
  #if pro user passes validations (email, password etc),
  # then call Stripe and tell Stripe to set up a subscription
  # upon charging the customer's card.
  # Stripe responds back with customer data.
  # Store customer.id as the customer token and save the user.
  
  def save_with_subscription
    #validate the fields email password password conf
    if valid?
    #if valid, then create a Stripe subscription for ongoing payments. NB if just a one time charge, this is not necessary as we will have received the card toke with the charge as a one off
    #because we are wanting a monthly fee, we need to create a customer at Strip and use the card token to create a subscription
    customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token) #Stripe will charge their card using the token that they gave us and create a subscription. Then call the rails server here and return an object of data. This is assigned to var customer
    
    #stripe_card_token for one time payments
    #stripe_customer_token for subscriptions
    
    #customer_token is the subscription id. That is what we keep
    #customer.id  is the customer_token
    #self is the user. stripe_customer_token is the field in the model and database
    self.stripe_customer_token = customer.id
    #now save the user to the database
    save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  #whitelist the following form fields so that we can process them, if coming from 
  #a devise sign up form
  before_action :configure_permitted_parameters,  if: :devise_controller?   #if a user submits a form from devise using the devise controller, then run configure_permitted_parameters
  
  protected 
    def configure_permitted_parameters
        #|u| refers to user
         devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) } #whitelist because we have added additional fields from the orignal devise form
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  #GET request to / contact-us
  #Show new contact form
  def new
    #everytime the new contact page is opened, a new object is created
    #and assigned to the variable @Contact
    @contact = Contact.new
  end
  
  #POST Request  / contacts
  #save
  def create
    #Mass assignment  of form fields into Contact object
    @contact = Contact.new(contact_params)
    #Save the Contact object into the database
    if @contact.save
      #Store form fields via parameters, into variables
      #send email
      #get fields from form
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      #Plug variables into Contact Mailer
      #email method and send email
      ContactMailer.contact_email(name, email, body).deliver
      
      #flash is the hash cache
      #success here is a key. It's value is set here
      #the page form access this key with <%= flash[:success] %>
      flash[:success] = "Message Sent."
      #Store success message in flash hash
      #and redirect to the new  action
      redirect_to new_contact_path
    else
      #If Contact object doesn't save,
      #store errors in flash has and redirect 
      #to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      #redirect_to new_contact_path, notice: "Error occurred."
      #when an error occurs @contacts will have accesss to .errors. errors are in an array
      #we split and join each error with a comma and space
      redirect_to new_contact_path
    end
  end
  
  private
    #To collect data from form we need to use strong parameters
    #and whitelist the form fields
    def contact_params
      #the below added to ensure security on the form fileds is maintained
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET request for /  which is our home page
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET to /users/:/user_id/profile/new
  def new
    # Render blank profile details form
    # in a .html.erb file you can ad debugging
    # <% debug(params) if Rails.env.development? %>
    
    @profile = Profile.new
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    #before and only for the new action go to the select_plan method to check that a plan has been added correctly
    before_action :select_plan, only: :new
    
    #inherit from Devise RegistrationsController
    #so that users signing up with the pro account (plan id2)
    #save with a special Stripe subscription function
    #otherwise devise signs up user as usual
    def create
      super do |resource| #super means inherit the 'create' action, but then extend it
        if params[:plan]
          #is there a parameter called param?
          resource.plan_id = params[:plan]  #resource means user in this case. So take whatever is in the form and set this users plan to be that plan id
          if(resource.plan_id == 2)  #so if the form is coming from the pro form, then don't just save the user. We also wanyt to keep the plan id. run the function that we create called save_with_subscription
            resource.save_with_subscription #write a user created function in the model. So in this case models/user.rb
            #the save is done in the model.
          else
            #otherwise just save as normal devise save
            resource.save
          end
        end
      end
    end
    
    private
    #for the user to have a plan
    def select_plan
      unless (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contact Us</h3>
    <div class="col-md-4 col-md-offset-4">
      <!--output a redirect to with notice message from controller
      < %= flash[:error] %> -->
      
      <!--more advanced output of hash flash-->
      <!-- This moved to main layout to ensure consistency in the whole site
      < % flash.each do |type, msg| %>
        < %= content_tag :div, msg, class: "alert alert-#{type}" %>
      < % end %>-->
      
      <div class="well">
    
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>            
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--<a href="/" class="navbar-brand"><i class="fa fa-group"></i> DevMatch</a>-->
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i> DevMatch
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? #user is logged in %>
              <% #show log out button %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: 'btn btn-default navbar-btn' %>
            <% end %>            
          </div>
          <ul class="nav navbar-nav navbar-right">
            <!--<li><a href="/about">About</a></li>-->
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
          </ul>
        </div>  <!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Page</h1>
    <p>We are DevMatch. Our company focuses on creating an exclusive community
    for developers and entrepreneurs to meet. </p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <h1>Welcome to DevMatch</h1>
    <h3>A Membership site where entrepreneurs can meet developers</h3>
</div>
<div class="container home-signup-links">
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Basic membership link</h2>
        <h4>Sign up for free and get basic access to the community</h4>
        <br />
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: "btn btn-primary btn-lrg btn-block" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Pro membership link</h2>
        <h4>Sign up for the pro account for £10/month and get access to the community and contact information</h4>
        <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: "btn btn-success btn-lrg btn-block" %>
      </div>
    </div>
  </div>
  
  <%= link_to "Create your profile!", new_user_profile_path(user_id: current_user.id) if user_signed_in? %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class "row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Be a part of the DevMatch community and fill out your profile!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>